- name: Generate stats card - light
  uses: readme-tools/github-readme-stats-action@v1
  with:
    card: stats
    options: username=${{ github.repository_owner }}&show_icons=true&theme=default
    path: profile/stats-light.svg
    token: ${{ secrets.GITHUB_TOKEN }}

- name: Generate stats card - dark
  uses: readme-tools/github-readme-stats-action@v1
  with:
    card: stats
    options: username=${{ github.repository_owner }}&show_icons=true&theme=dark
    path: profile/stats-dark.svg
    token: ${{ secrets.GITHUB_TOKEN }}

- name: Generate top-langs card - light
  uses: readme-tools/github-readme-stats-action@v1
  with:
    card: top-langs
    options: username=${{ github.repository_owner }}&layout=compact&langs_count=7&theme=default
    path: profile/top-langs-light.svg
    token: ${{ secrets.GITHUB_TOKEN }}

- name: Generate top-langs card - dark
  uses: readme-tools/github-readme-stats-action@v1
  with:
    card: top-langs
    options: username=${{ github.repository_owner }}&layout=compact&langs_count=7&theme=dark
    path: profile/top-langs-dark.svg
    token: ${{ secrets.GITHUB_TOKEN }}
